// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfRHL79HSRqUa0ZF1SyelVUEmARJPhi4I',
    appId: '1:541633265065:web:159e200fb468de02c598b8',
    messagingSenderId: '541633265065',
    projectId: 'xiaomin-3035f',
    authDomain: 'xiaomin-3035f.firebaseapp.com',
    storageBucket: 'xiaomin-3035f.appspot.com',
    measurementId: 'G-GBD0DQ03PS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkwXIv1ULA7UzVqvgKCE4VYF_3p49TrA8',
    appId: '1:541633265065:android:75d067f2c4150ec0c598b8',
    messagingSenderId: '541633265065',
    projectId: 'xiaomin-3035f',
    storageBucket: 'xiaomin-3035f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvlf5hi1FX-RDsz5_wBiJfW3FhnUjyh7Y',
    appId: '1:541633265065:ios:a1e19e7dd7abd7cdc598b8',
    messagingSenderId: '541633265065',
    projectId: 'xiaomin-3035f',
    storageBucket: 'xiaomin-3035f.appspot.com',
    iosClientId: '541633265065-ccno3uem1iavl9c55j7cs3tv3vui4o5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvlf5hi1FX-RDsz5_wBiJfW3FhnUjyh7Y',
    appId: '1:541633265065:ios:a1e19e7dd7abd7cdc598b8',
    messagingSenderId: '541633265065',
    projectId: 'xiaomin-3035f',
    storageBucket: 'xiaomin-3035f.appspot.com',
    iosClientId: '541633265065-ccno3uem1iavl9c55j7cs3tv3vui4o5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );
}
